use std::convert::From;

#[derive(Copy, Clone, PartialEq, Eq)]
pub enum LanguageId {
    CodeArray,
    Language(u16),
}

impl From<u16> for LanguageId {
    fn from(value: u16) -> Self {
        if value == 0 {
            Self::CodeArray
        } else {
            Self::Language(value)
        }
    }
}
impl std::fmt::Debug for LanguageId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::CodeArray => write!(f, "CodeArray"),
            Self::Language(lang_id) => match lang_id {
                0x0436 => write!(f, "{:?}", "Afrikaans"),
                0x041c => write!(f, "{:?}", "Albanian"),
                0x0401 => write!(f, "{:?}", "Arabic (Saudi Arabia)"),
                0x0801 => write!(f, "{:?}", "Arabic (Iraq)"),
                0x0c01 => write!(f, "{:?}", "Arabic (Egypt)"),
                0x1001 => write!(f, "{:?}", "Arabic (Libya)"),
                0x1401 => write!(f, "{:?}", "Arabic (Algeria)"),
                0x1801 => write!(f, "{:?}", "Arabic (Morocco)"),
                0x1c01 => write!(f, "{:?}", "Arabic (Tunisia)"),
                0x2001 => write!(f, "{:?}", "Arabic (Oman)"),
                0x2401 => write!(f, "{:?}", "Arabic (Yemen)"),
                0x2801 => write!(f, "{:?}", "Arabic (Syria)"),
                0x2c01 => write!(f, "{:?}", "Arabic (Jordan)"),
                0x3001 => write!(f, "{:?}", "Arabic (Lebanon)"),
                0x3401 => write!(f, "{:?}", "Arabic (Kuwait)"),
                0x3801 => write!(f, "{:?}", "Arabic (U.A.E.)"),
                0x3c01 => write!(f, "{:?}", "Arabic (Bahrain)"),
                0x4001 => write!(f, "{:?}", "Arabic (Qatar)"),
                0x042b => write!(f, "{:?}", "Armenian."),
                0x044d => write!(f, "{:?}", "Assamese."),
                0x042c => write!(f, "{:?}", "Azeri (Latin)"),
                0x082c => write!(f, "{:?}", "Azeri (Cyrillic)"),
                0x042d => write!(f, "{:?}", "Basque"),
                0x0423 => write!(f, "{:?}", "Belarussian"),
                0x0445 => write!(f, "{:?}", "Bengali."),
                0x0402 => write!(f, "{:?}", "Bulgarian"),
                0x0455 => write!(f, "{:?}", "Burmese"),
                0x0403 => write!(f, "{:?}", "Catalan"),
                0x0404 => write!(f, "{:?}", "Chinese (Taiwan)"),
                0x0804 => write!(f, "{:?}", "Chinese (PRC)"),
                0x0c04 => write!(f, "{:?}", "Chinese (Hong Kong SAR, PRC)"),
                0x1004 => write!(f, "{:?}", "Chinese (Singapore)"),
                0x1404 => write!(f, "{:?}", "Chinese (Macau SAR)"),
                0x041a => write!(f, "{:?}", "Croatian"),
                0x0405 => write!(f, "{:?}", "Czech"),
                0x0406 => write!(f, "{:?}", "Danish"),
                0x0413 => write!(f, "{:?}", "Dutch (Netherlands)"),
                0x0813 => write!(f, "{:?}", "Dutch (Belgium)"),
                0x0409 => write!(f, "{:?}", "English (United States)"),
                0x0809 => write!(f, "{:?}", "English (United Kingdom)"),
                0x0c09 => write!(f, "{:?}", "English (Australian)"),
                0x1009 => write!(f, "{:?}", "English (Canadian)"),
                0x1409 => write!(f, "{:?}", "English (New Zealand)"),
                0x1809 => write!(f, "{:?}", "English (Ireland)"),
                0x1c09 => write!(f, "{:?}", "English (South Africa)"),
                0x2009 => write!(f, "{:?}", "English (Jamaica)"),
                0x2409 => write!(f, "{:?}", "English (Caribbean)"),
                0x2809 => write!(f, "{:?}", "English (Belize)"),
                0x2c09 => write!(f, "{:?}", "English (Trinidad)"),
                0x3009 => write!(f, "{:?}", "English (Zimbabwe)"),
                0x3409 => write!(f, "{:?}", "English (Philippines)"),
                0x0425 => write!(f, "{:?}", "Estonian"),
                0x0438 => write!(f, "{:?}", "Faeroese"),
                0x0429 => write!(f, "{:?}", "Farsi"),
                0x040b => write!(f, "{:?}", "Finnish"),
                0x040c => write!(f, "{:?}", "French (Standard)"),
                0x080c => write!(f, "{:?}", "French (Belgian)"),
                0x0c0c => write!(f, "{:?}", "French (Canadian)"),
                0x100c => write!(f, "{:?}", "French (Switzerland)"),
                0x140c => write!(f, "{:?}", "French (Luxembourg)"),
                0x180c => write!(f, "{:?}", "French (Monaco)"),
                0x0437 => write!(f, "{:?}", "Georgian."),
                0x0407 => write!(f, "{:?}", "German (Standard)"),
                0x0807 => write!(f, "{:?}", "German (Switzerland)"),
                0x0c07 => write!(f, "{:?}", "German (Austria)"),
                0x1007 => write!(f, "{:?}", "German (Luxembourg)"),
                0x1407 => write!(f, "{:?}", "German (Liechtenstein)"),
                0x0408 => write!(f, "{:?}", "Greek"),
                0x0447 => write!(f, "{:?}", "Gujarati."),
                0x040d => write!(f, "{:?}", "Hebrew"),
                0x0439 => write!(f, "{:?}", "Hindi."),
                0x040e => write!(f, "{:?}", "Hungarian"),
                0x040f => write!(f, "{:?}", "Icelandic"),
                0x0421 => write!(f, "{:?}", "Indonesian"),
                0x0410 => write!(f, "{:?}", "Italian (Standard)"),
                0x0810 => write!(f, "{:?}", "Italian (Switzerland)"),
                0x0411 => write!(f, "{:?}", "Japanese"),
                0x044b => write!(f, "{:?}", "Kannada."),
                0x0860 => write!(f, "{:?}", "Kashmiri (India)"),
                0x043f => write!(f, "{:?}", "Kazakh"),
                0x0457 => write!(f, "{:?}", "Konkani."),
                0x0412 => write!(f, "{:?}", "Korean"),
                0x0812 => write!(f, "{:?}", "Korean (Johab)"),
                0x0426 => write!(f, "{:?}", "Latvian"),
                0x0427 => write!(f, "{:?}", "Lithuanian"),
                0x0827 => write!(f, "{:?}", "Lithuanian (Classic)"),
                0x042f => write!(f, "{:?}", "Macedonian"),
                0x043e => write!(f, "{:?}", "Malay (Malaysian)"),
                0x083e => write!(f, "{:?}", "Malay (Brunei Darussalam)"),
                0x044c => write!(f, "{:?}", "Malayalam."),
                0x0458 => write!(f, "{:?}", "Manipuri"),
                0x044e => write!(f, "{:?}", "Marathi."),
                0x0861 => write!(f, "{:?}", "Nepali (India)."),
                0x0414 => write!(f, "{:?}", "Norwegian (Bokmal)"),
                0x0814 => write!(f, "{:?}", "Norwegian (Nynorsk)"),
                0x0448 => write!(f, "{:?}", "Oriya."),
                0x0415 => write!(f, "{:?}", "Polish"),
                0x0416 => write!(f, "{:?}", "Portuguese (Brazil)"),
                0x0816 => write!(f, "{:?}", "Portuguese (Standard)"),
                0x0446 => write!(f, "{:?}", "Punjabi."),
                0x0418 => write!(f, "{:?}", "Romanian"),
                0x0419 => write!(f, "{:?}", "Russian"),
                0x044f => write!(f, "{:?}", "Sanskrit."),
                0x0c1a => write!(f, "{:?}", "Serbian (Cyrillic)"),
                0x081a => write!(f, "{:?}", "Serbian (Latin)"),
                0x0459 => write!(f, "{:?}", "Sindhi"),
                0x041b => write!(f, "{:?}", "Slovak"),
                0x0424 => write!(f, "{:?}", "Slovenian"),
                0x040a => write!(f, "{:?}", "Spanish (Traditional Sort)"),
                0x080a => write!(f, "{:?}", "Spanish (Mexican)"),
                0x0c0a => write!(f, "{:?}", "Spanish (Modern Sort)"),
                0x100a => write!(f, "{:?}", "Spanish (Guatemala)"),
                0x140a => write!(f, "{:?}", "Spanish (Costa Rica)"),
                0x180a => write!(f, "{:?}", "Spanish (Panama)"),
                0x1c0a => write!(f, "{:?}", "Spanish (Dominican Republic)"),
                0x200a => write!(f, "{:?}", "Spanish (Venezuela)"),
                0x240a => write!(f, "{:?}", "Spanish (Colombia)"),
                0x280a => write!(f, "{:?}", "Spanish (Peru)"),
                0x2c0a => write!(f, "{:?}", "Spanish (Argentina)"),
                0x300a => write!(f, "{:?}", "Spanish (Ecuador)"),
                0x340a => write!(f, "{:?}", "Spanish (Chile)"),
                0x380a => write!(f, "{:?}", "Spanish (Uruguay)"),
                0x3c0a => write!(f, "{:?}", "Spanish (Paraguay)"),
                0x400a => write!(f, "{:?}", "Spanish (Bolivia)"),
                0x440a => write!(f, "{:?}", "Spanish (El Salvador)"),
                0x480a => write!(f, "{:?}", "Spanish (Honduras)"),
                0x4c0a => write!(f, "{:?}", "Spanish (Nicaragua)"),
                0x500a => write!(f, "{:?}", "Spanish (Puerto Rico)"),
                0x0430 => write!(f, "{:?}", "Sutu"),
                0x0441 => write!(f, "{:?}", "Swahili (Kenya)"),
                0x041d => write!(f, "{:?}", "Swedish"),
                0x081d => write!(f, "{:?}", "Swedish (Finland)"),
                0x0449 => write!(f, "{:?}", "Tamil."),
                0x0444 => write!(f, "{:?}", "Tatar (Tatarstan)"),
                0x044a => write!(f, "{:?}", "Telugu."),
                0x041e => write!(f, "{:?}", "Thai"),
                0x041f => write!(f, "{:?}", "Turkish"),
                0x0422 => write!(f, "{:?}", "Ukrainian"),
                0x0420 => write!(f, "{:?}", "Urdu (Pakistan)"),
                0x0820 => write!(f, "{:?}", "Urdu (India)"),
                0x0443 => write!(f, "{:?}", "Uzbek (Latin)"),
                0x0843 => write!(f, "{:?}", "Uzbek (Cyrillic)"),
                0x042a => write!(f, "{:?}", "Vietnamese"),
                0x04ff => write!(f, "{:?}", "HID (Usage Data Descriptor)"),
                0xf0ff => write!(f, "{:?}", "HID (Vendor Defined 1)"),
                0xf4ff => write!(f, "{:?}", "HID (Vendor Defined 2)"),
                0xf8ff => write!(f, "{:?}", "HID (Vendor Defined 3)"),
                0xfcff => write!(f, "{:?}", "HID (Vendor Defined 4)"),
                _ => write!(f, "Reserved id ({})", lang_id),
            },
        }
    }
}
